site_name: nuMCMC
site_description: Documentation for the nuMCMC C++ library
site_author: nuMCMC Contributors

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - About: about.md

docs_dir: docs

plugins: []
